model:
  _target_: src.models.eccv_module.ViSTModule
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0008
    weight_decay: 0.1
  scheduler:
    _target_: src.lr_schedulers.OneCycleCos.OneCycleCos
    _partial_: true
    lr_min: 0.0001
    lr_start: 5.0e-05
    lr_max: ${model.optimizer.lr}
    milestones: 5
    T_max: ${trainer.max_epochs}
    verbose: true
  net:
    _target_: src.models.components.eccv.ViST
    video_layers: 6
    video_dim: 256
    dinov2_dim: 1024
    cells: ${model.index_length}
    grids: 16
    causal: true
  featrue_key: dinov2_feats_0
  indeces: null
  index_start: 0
  index_length: 90
model/params/total: 1702952
model/params/trainable: 1702952
model/params/non_trainable: 0
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 30
  limit_train_batches: 48
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  check_val_every_n_epoch: 1
  deterministic: false
  enable_model_summary: false
  plugins:
    _target_: src.utils.checkpointio.AsyncTorchCheckpointIO
  num_sanity_val_steps: 0
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val/corr
    verbose: false
    save_last: true
    save_top_k: 1
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: 5
    save_on_train_epoch_end: null
  vae_prediction_writer:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: epoch
    log_momentum: false
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: 0
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
  swa:
    _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
    swa_lrs: 0.0001
    swa_epoch_start: 20
    annealing_epochs: 5
    annealing_strategy: cos
  learning_rate_monitor:
    logging_interval: epoch
extras:
  ignore_warnings: false
  enforce_tags: true
  print_config: true
task_name: eccv2
tags:
- eccv
ckpt_path: null
seed: null
