# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.BasePredictionWriter.html

swa:
  _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
  swa_lrs: ??? # learning rates for the SWA optimizer
  swa_epoch_start: 0.8
  annealing_epochs: 10
  annealing_strategy: "cos"
